theme = "catppuccin_mocha"
# theme = "onedarker"

[editor]
#line-number = "relative"
mouse = true
bufferline = "always"
color-modes = true
true-color = true
# end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
# C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme onedark", ":theme default" ]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80%% -h80%% -E lazygit"
C-l = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
C-y = [
      ':sh rm -f /tmp/unique-file',
      ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
      ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
      ':open %sh{cat /tmp/unique-file}',
      ':redraw',
      ':set mouse false',
      ':set mouse true',
]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-n = ":n"
C-o = ":config-open"
C-r = ":config-reload"
C-t = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80%% -h80%%"
C-x = ":o ~/.config/helix/languages.toml"
# "C-/" = "toggle_comments"
"C-s" = ":w"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"


[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
C-c = ["normal_mode", "toggle_comments", "insert_mode"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

