# Languages configuration

[[language]]
name = "python"
language-servers = ["ruff", "pylsp", "gpt"]
formatter = { command = "ruff", args = ["format", "--line-length", "120", "-"] }
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true

[language-server.ruff.config.settings]
lineLength = 120

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.gpt]
command = "helix-gpt"
